services:
  app:
    hostname: duckscatter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
      - dist:/workspace/dist
      - next_node_modules:/workspace/examples/next/node_modules
      - next_dot_next:/workspace/examples/next/.next
    working_dir: /workspace

volumes:
  node_modules:
  dist:
  next_node_modules:
  next_dot_next:
